### ISSUE TITLE
Provide photometric zeropoints

### ISSUE THREAD

**Issue by mrtommyb** [spacetelescope/roman-technical-information#11]
Various users have asked for photometric zeropoint magnitudes. We should add them to this repo.

**Comment by tddesjardins** [comment]
We computed these at the SOC using the filter throughputs. I could do the same and add them back here using the updated throughputs + detector QE info and in various systems (e.g., Vega, AB). Any preferences?

Note: I had been holding off a bit on this to get the updated values from TVAC2 from Maxime et al. If there is interest, though, I'm fine to proceed and just update again later.
