### ISSUE TITLE
Roman Space Telescope Primary Mirror Diameter

### ISSUE THREAD

**Issue by sepito** [spacetelescope/roman-technical-information#14]
As advised per Rob Zellem, I post the question here.

We list the telescope primary mirror diameter as 2.36 m, you give just 2.4 m in the technical information page. Is 2.36 m too accurate?

Thanks, Seppo

**Comment by mrtommyb** [comment]
@rzellem can you get the answer here?

**Comment by rzellem** [comment]
@sepito - I'm seeing it listed as 2.4-m here:

https://github.com/spacetelescope/roman-technical-information/blob/main/data/Observatory/MissionandObservatoryTechnicalOverview/MissionandObservatory.yaml

and I've only seen it as being described as 2.4-m --- where are you seeing 2.36-m?

**Comment by sepito** [comment]
Here. This must have come from Jeff Kruk several years ago. Can you check?
https://roman.ipac.caltech.edu/sims/Param_db.html

**Comment by rzellem** [comment]
Got it. I'll let you know what I find out.

**Comment by rzellem** [comment]
@sepito - you are correct. While the mirror's diameter is 2.4-m, there is an aperture stop that effectively decreases the mirror diameter to 2.36-m. I'll update the diameter to 2.36-m. Thanks!
