### ISSUE TITLE
Microlensing Maximum Slew Angle/Time?

### ISSUE THREAD

**Issue by sepito** [spacetelescope/roman-technical-information#15]
As per request from Rob Zellem:

We have something on the IPAC Roman Parameter page at https://roman.ipac.caltech.edu/sims/Param_db.html called  Spacecraft_Slew_Angle/Time_Microlensing_Maximum with values of 2.06 deg/99 seconds. I don't see that mentioned in the technical information pages. Should we take it out or can you verify it and add it into the technical information pages?

Thanks much, Seppo

**Comment by mrtommyb** [comment]
I think we can close this with no changes. The slew/settle times listed are accurate and the 2.06 degree slew can we inferred from the values currently listed.
