### ISSUE TITLE
Wrong information about prism spectroscopy sensitivity description in Roman Technical Information GitHub site

### ISSUE THREAD

**Issue by sepito** [spacetelescope/roman-technical-information#17]
As per request by Rob Zellem:

On https://github.com/spacetelescope/roman-technical-information/blob/main/data/WideFieldInstrument/Spectroscopy/Sensitivity/prism_spectroscopy_sensitivity.ecsv the code lines 8 and 9 appear to be wrong (it should be for 62 sec exposure time, not 1-hour). Line eight should not talk about a compact galaxy either or line flux values.

Thanks again,

Seppo

**Comment by mrtommyb** [comment]
@rzellem can you look into this?

**Comment by rzellem** [comment]
I think my original text about the r50=0 being a point source and r50=0.3" being a compact galaxy is correct - as under Imaging Sensitivity it says that for the table below, it has labels called "Point" and "r50=0.3" with explanatory text:

"The table below gives the 5-sigma AB magnitude limiting sensitivity, for twice the minimum zodiacal light background (roughly equivalent to that obtained at an ecliptic latitude of 25 degrees at a Solar elongation of 90 degrees), for 57 second and one-hour integrations, for point sources and a compact galaxy with half-light radius of 0.3 arcseconds."

please double check this, @sepito, as I might be misinterpreting it myself


I do agree with you that I did make a typo on the time label and I can fix that

**Comment by sepito** [comment]
Lines 7 and 9 refer to the galaxy sensitivity, so they should have the compact galaxy if I am reading the table correctly (in Table these correspond to columns 4 and 6 that are labeled "mAB_galaxy_one_hr," and "mAB_galaxy_sixty_two_sec". I think line 7 should say "# - {name: mAB_galaxy_one_hr, unit: ABmag, datatype: float64, description: 5-sigma detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy's (with half-light radius of 0.3 arcseconds) continuum in units of AB magnitude", line 8 should say "# - {name: mAB_point_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma detection limit for a 62=-second exposure time with zodiacal light background at twice the minimum intensity for a point source's continuum in units of AB magnitude" and the lines 6 and 9 should be corrected accordingly (line 6 "point source's continuum" and drop "at which S/N=5 per pixel"}). I think you should drop "at which S/N=5 per pixel" from all of them. And line 9 would change "1-hour" to "62-second" and "continuum in units of AB magnitude" at the end. Can you make those changes and then I can look at it again?

**Comment by rzellem** [comment]
I think we need to keep the S/N=5 per pixel - that's in the caption just above the prism table:

"The Table below has AB at which S/N=5 per pixel"


Here's what I suggest we update the original text to:

```
# - {name: mAB_point_one_hr, unit: ABmag, datatype: float64, description: 5-sigma detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a point source in units of AB magnitude at which S/N=5 per pixel.}
# - {name: mAB_galaxy_one_hr, unit: ABmag, datatype: float64, description: 5-sigma detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy in units of AB magnitude at which S/N=5 per pixel.}
# - {name: mAB_point_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma detection limit for a 62-second exposure time with zodiacal light background at twice the minimum intensity for a point source in units of AB magnitude at which S/N=5 per pixel.}
# - {name: mAB_galaxy_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma detection limit for a 62-second exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy in units of AB magnitude at which S/N=5 per pixel.}
```

**Comment by sepito** [comment]
What confuses me is that we seem to say that it is a 5-sigma detection limit for a point source but then every pixel is detected at 5 sigma too...that doesn't sound consistent to me. The way we word this on the IPAC's Roman parameter page is "WFI prism limiting point source sensitivity (10-sigma per pixel in continuum) at 0.8 microns in 1 hour of exposure time, zodiacal light set at twice the minimum value". Would that be acceptable (after changing 10-sigma to 5-sigma)? And should we add the "(with half-light radius of 0.3 arcseconds)" for the galaxy value descriptions as well? I'll ask around here at SSC as well what they think about the wording.

**Comment by rzellem** [comment]
that's a great point about the "5-sigma" and "S/R = 5", @sepito - I'll take another look at the text and see if I can figure it out

I'll also ping Jeff to confirm the language- let me know what folks think at SSC!

thanks so much!

**Comment by rzellem** [comment]
I think that the 5-sigma detection limit is *always* over 1-pixel for this entire table - so it isn't that the point source at a whole is at 5-sigma, rather it's a single pixel.

**Comment by rzellem** [comment]
hi @sepito - I ran these tweaked descriptions

```
# - {name: mAB_point_one_hr, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a point source in units of AB magnitude (mAB) at which S/N=5 per pixel.}

# - {name: mAB_galaxy_one_hr, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy in units of AB magnitude (mAB) at which S/N=5 per pixel.}

# - {name: mAB_point_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 62-second exposure time with zodiacal light background at twice the minimum intensity for a point source in units of AB magnitude (mAB) at which S/N=5 per pixel.}

# - {name: mAB_galaxy_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 62-second exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy in units of AB magnitude (mAB) at which S/N=5 per pixel.}
```


across Jeff Kruk and here's what he said:


> Jeffrey Kruk
>   2:01 PM
> I think the descriptions are fine, though I suggest being more explicit about galaxy size: these cases are for an exponential disk with half-light radius=0.3".

So based on his feedback, I recommend we use this instead:


```
# - {name: mAB_point_one_hr, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a point source in units of AB magnitude (mAB).}

# - {name: mAB_galaxy_one_hr, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 1-hour exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy (an exponential disk with half-light radius=0.3") in units of AB magnitude (mAB).}

# - {name: mAB_point_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 62-second exposure time with zodiacal light background at twice the minimum intensity for a point source in units of AB magnitude (mAB).}

# - {name: mAB_galaxy_sixty_two_sec, unit: ABmag, datatype: float64, description: 5-sigma (per pixel) detection limit for a 62-second exposure time with zodiacal light background at twice the minimum intensity for a compact galaxy (an exponential disk with half-light radius=0.3") in units of AB magnitude (mAB).}

```

Sound good to you, @sepito ?

**Comment by sepito** [comment]
Sounds good to me. Maybe that "mAB" at the end could be "m_AB" to prevent people from thinking milli-magnitudes or something like that. Thanks!
