### ISSUE TITLE
Do we really need all of these nested READMEs?

### ISSUE THREAD

**Issue by rzellem** [spacetelescope/roman-technical-information#20]
Right now, I have README.md files in *every single folder*. Is this truly necessary? I'm particularly worried that if we make a change in a nested folder, we have to not only update the README in that folder, but also the folders containing them.

So for example, when I update `MissionanObservatory.yaml` in the `roman-technical-information/data/Observatory/MissionandObservatoryTechnicalOverivew/` folder, I have to edit the "date" field in the README files in the `data`, `Observatory`, and `MissionandObservatoryTechnicalOverivew` folders. Which can be a pain and potentially result in incorrect dates.

Instead, I propose to have a single README in the final child folder- so in the above example, there would only be a single README in `MissionandObservatoryTechnicalOverview` folder and none in the "parent" folders.

What do y'all think?

**Comment by sepito** [comment]
Your suggestion sounds good to me. I never read the Readme files anyway unless absolutely necessary.

**Comment by rzellem** [comment]
Thanks, @sepito - that's my thought as well. Anyone else feel strongly either way? @mrtommyb @tddesjardins @rachael-beaton others?

**Comment by tddesjardins** [comment]
I also agree that your proposal makes sense. Thanks for that!

**Comment by rachael-beaton** [comment]
Yes -- that makes sense. I would think you could keep the readme.md to have general words, but no specific words. err does that make sense. "This file is" if it isn't clear, but right no updates.

**Comment by mrtommyb** [comment]
I agree that we have too many readme's it seemed like a good idea at the time. I wonder if we should remove all the lowest level readme files, and put all that information in the higher level ones

**Comment by tddesjardins** [comment]
Well, @mrtommyb and @rzellem 's suggestions seem to be the exact opposite of each other. I'm not fussed either way personally, I just like the idea of reducing the number of them. What should we do?

**Comment by mrtommyb** [comment]
This is now being tracked on #27
