### ISSUE TITLE
Update language for ND filters

### ISSUE THREAD

**Issue by rzellem** [spacetelescope/roman-technical-information#22]
from @sepito :

> The only recommendation is to add some description for the neutral density filters (IPAC website has for example "Attenuation factor of Neutral Density filter used for target acquisition (ND 2.25) mounted in FPAM" etc.

**Comment by rzellem** [comment]
Sounds good. I can add that language. As a heads up, the FSAM is *not* used for target acquisition (I believe that I'm using that for absolute flux calibrations...but I cannot confirm right now as I cannot get on to the JPL VPN). @sepito - would you mind removing the text about the FSAM ND4.75 filter being used for acquisition from the IPAC website, please?

**Comment by sepito** [comment]
So the parameter to be removed is CGI_Bandpass_ND_4pt75_FSAM? I can do that but I think we'd prefer to make all these parameter updates at once as it is a somewhat involved process...so can this wait until I have confirmation on the questions that I submitted to you and Tom on GitHub? I'm curious also if Jeff Kruk is OK with our description language for those prism spectral continuum sensitivity parameters. Thanks!

**Comment by rzellem** [comment]
Happy for you to wait - I need to also verify/update the CGI parameters as well. I'll be doing that over the next few days and get back to you.

I haven't heard back from Jeff yet about our labeling question.

**Comment by rzellem** [comment]
@sepito - can I close this issue? the ND filter descriptions are now correct here on the Github.

**Comment by sepito** [comment]
It is much more sparse language than what we have on the SSC website but I think all the essential information is there so OK to close. Thanks!
