### ISSUE TITLE
FWHM in arcsec vs effective number of pixels

### ISSUE THREAD

**Issue by benjaminrose** [spacetelescope/roman-technical-information#26]
Looking at the documentation for the PSF, we see both a "PSF FWHM (arcsec)" and "n eff pixel". However, if you assume a Gaussian, these are off by an order of magnitude. I would expect a factor of 2 but not a factor of 10.
 
 For F062:
 - FWHM = 0.058 arcsec
 - sigma = 0.058/2.355 = 0.0246 arcsec
 - NEA(arcsec) = 4\pi\sigma^2 = 0.007622 arcsec^2 NEA(pix) = NEA(arcsec)/0.11^2 = 0.63 pix^2
 - However the website says the "n eff pixel" is 3.80–7.35 pix. Can you explain this difference?

**Comment by mrtommyb** [comment]
I don't think that NEA is the correct term here. I am used to that term in reference to centroiding.

I reached out to Jeff Kruk who generated these tables and his was response was that what you calculated is the integral of a Gaussian of unit peak flux. The “N eff pix” is also known as “noise pixels” and is the number of pixels contributing noise to the measured flux when doing PSF fitting.  If PSF[i,j] is the PSF normalized to unit total flux, not unit peak amplitude, then n_eff_pix = 1/SUM(PSF[i,j]^2). This is the inverse of the “sharpness” of a PSF.  It is important to calculate this on physical pixels. If you calculate it on sub-sampled pixels, or infinitely sampled as in calculating an analytic function like a gaussian you get a different result that is not relevant when computing SNR.

**Comment by mrtommyb** [comment]
@benjaminrose does this answer your question?
