### ISSUE TITLE
Provide updated slew and settle times

### ISSUE THREAD

**Issue by mrtommyb** [spacetelescope/roman-technical-information#3]
The currently available slew and settle times are online on the [GSFC technical site](https://roman.gsfc.nasa.gov/science/field_slew_and_roll.html#slewtable). These are outdated values. We should update these with the latest values.

**Comment by mrtommyb** [comment]
So I think we can close this, @sepito

**Comment by sepito** [comment]
I guess I'll just delete those small and large settling times in our parameter listing. Done. You can close this! Thanks.
